language: c
matrix:
  include:
    - os: windows
      language: sh
      filter_secrets: false

script:
  - git clone --depth=50 --branch=master https://github.com/vlang/v.git
  - cd v
  - echo "Running make.bat..."
  - ./make.bat
  - ./v.exe -debug -o v2.exe compiler

addons:
  artifacts: true
    paths:
    - $HOME/v/v.exe
